import type { AppLanguage, EntryFont } from "./types";

export const COPY = {
  ar: { diary: "المذكرات", memories: "الذكريات", settings: "الإعدادات", welcome: "مساحتك الخاصة", today: "اليوم", newMemory: "ذكرى جديدة", noMemories: "لم تُكتب ذكرى بعد", startWriting: "اكتبي أو اكتب أول ذكرى لك", recent: "آخر الذكريات", createMemory: "إنشاء ذكرى", editMemory: "تعديل الذكرى", title: "العنوان", titlePlaceholder: "عنوان صغير لذكراك", body: "النص", bodyPlaceholder: "اكتب ما تريد أن تتذكره…", save: "حفظ الذكرى", saved: "تم الحفظ", cancel: "إلغاء", delete: "حذف", edit: "تعديل", voiceNote: "ملاحظة صوتية", record: "تسجيل", stop: "إيقاف", play: "تشغيل", pause: "إيقاف مؤقت", font: "الخط", appearance: "المظهر", blossom: "وردي مزهر", noir: "داكن متماسك", language: "اللغة", defaultFont: "الخط الافتراضي", privacy: "الخصوصية", changeLock: "تغيير رمز القفل", setupTitle: "دفترك لا يراه سواك", setupBody: "اختَر حماية محلية قبل حفظ أول ذكرى. لا نستخدم حساباً أو خادماً.", choosePin: "رمز من 4 أرقام", choosePassword: "كلمة مرور", confirmPin: "أعد إدخال الرمز", confirmPassword: "أعد كتابة كلمة المرور", enterPin: "أدخل رمزك", enterPassword: "أدخل كلمة المرور", unlock: "فتح المذكرات", createLock: "حفظ الحماية", mismatch: "الإدخالان غير متطابقين.", invalidPin: "يتكوّن الرمز من أربعة أرقام.", wrongLock: "رمز الحماية غير صحيح.", locked: "مقفلة بأمان", localOnly: "محفوظ محلياً على جهازك", searchPlaceholder: "ابحث في الذكريات", noResults: "لا توجد نتائج", requiredBody: "اكتب عنواناً أو نصاً قبل الحفظ.", recordingUnavailable: "تعذّر الوصول إلى الميكروفون." },
  fr: { diary: "Journal", memories: "Souvenirs", settings: "Réglages", welcome: "Votre espace privé", today: "Aujourd’hui", newMemory: "Nouveau souvenir", noMemories: "Aucun souvenir pour l’instant", startWriting: "Écrivez votre premier souvenir", recent: "Souvenirs récents", createMemory: "Créer un souvenir", editMemory: "Modifier le souvenir", title: "Titre", titlePlaceholder: "Un petit titre pour ce souvenir", body: "Texte", bodyPlaceholder: "Écrivez ce que vous souhaitez garder…", save: "Enregistrer", saved: "Enregistré", cancel: "Annuler", delete: "Supprimer", edit: "Modifier", voiceNote: "Note vocale", record: "Enregistrer", stop: "Arrêter", play: "Lire", pause: "Pause", font: "Police", appearance: "Apparence", blossom: "Rose fleuri", noir: "Sombre sobre", language: "Langue", defaultFont: "Police par défaut", privacy: "Confidentialité", changeLock: "Modifier le verrou", setupTitle: "Ce journal est à vous", setupBody: "Choisissez une protection locale avant votre premier souvenir. Aucun compte ni serveur n’est utilisé.", choosePin: "Code à 4 chiffres", choosePassword: "Mot de passe", confirmPin: "Confirmez le code", confirmPassword: "Confirmez le mot de passe", enterPin: "Entrez votre code", enterPassword: "Entrez votre mot de passe", unlock: "Ouvrir le journal", createLock: "Enregistrer la protection", mismatch: "Les deux saisies ne correspondent pas.", invalidPin: "Le code doit contenir quatre chiffres.", wrongLock: "La protection est incorrecte.", locked: "Verrouillé en toute sécurité", localOnly: "Enregistré localement sur cet appareil", searchPlaceholder: "Rechercher dans les souvenirs", noResults: "Aucun résultat", requiredBody: "Ajoutez un titre ou un texte avant d’enregistrer.", recordingUnavailable: "Accès au microphone impossible." },
  en: { diary: "Diary", memories: "Memories", settings: "Settings", welcome: "Your private space", today: "Today", newMemory: "New memory", noMemories: "No memories yet", startWriting: "Write your first memory", recent: "Recent memories", createMemory: "Create memory", editMemory: "Edit memory", title: "Title", titlePlaceholder: "A small title for this memory", body: "Text", bodyPlaceholder: "Write what you would like to remember…", save: "Save memory", saved: "Saved", cancel: "Cancel", delete: "Delete", edit: "Edit", voiceNote: "Voice note", record: "Record", stop: "Stop", play: "Play", pause: "Pause", font: "Font", appearance: "Appearance", blossom: "Blossom pink", noir: "Solid dark", language: "Language", defaultFont: "Default font", privacy: "Privacy", changeLock: "Change lock", setupTitle: "Your diary is only yours", setupBody: "Choose local protection before saving a first memory. No account or server is used.", choosePin: "4-digit PIN", choosePassword: "Password", confirmPin: "Confirm PIN", confirmPassword: "Confirm password", enterPin: "Enter your PIN", enterPassword: "Enter your password", unlock: "Open diary", createLock: "Save protection", mismatch: "The two values do not match.", invalidPin: "Your PIN must contain four digits.", wrongLock: "That protection code is not correct.", locked: "Locked safely", localOnly: "Stored locally on this device", searchPlaceholder: "Search memories", noResults: "No results", requiredBody: "Add a title or text before saving.", recordingUnavailable: "Microphone access was not available." },
} as const;

export function getCopy(language: AppLanguage) { return COPY[language]; }
export function fontName(font: EntryFont, language: AppLanguage) { return ({ classic: { ar: "كلاسيكي", fr: "Classique", en: "Classic" }, clean: { ar: "هادئ", fr: "Épuré", en: "Clean" }, mono: { ar: "أحادي", fr: "Mono", en: "Mono" } } as const)[font][language]; }
export function languageName(language: AppLanguage, displayLanguage: AppLanguage) { return ({ ar: { ar: "العربية", fr: "Arabe", en: "Arabic" }, fr: { ar: "الفرنسية", fr: "Français", en: "French" }, en: { ar: "الإنجليزية", fr: "Anglais", en: "English" } } as const)[language][displayLanguage]; }
