import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { type ComponentProps } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { MoodBadge } from "@/components/imanote/mood-tags";
import { wellbeingCopy } from "@/lib/imanote/copy";
import { useDiary } from "@/lib/imanote/diary-context";
import { deriveWellbeingInsights } from "@/lib/imanote/insights";
import { MOOD_IDS } from "@/lib/imanote/types";

export default function InsightsScreen() {
  const { entries, palette, settings, isRTL } = useDiary(); const copy = wellbeingCopy(settings.language); const insights = deriveWellbeingInsights(entries); const maxDaily = Math.max(1, ...insights.week.map((day) => day.total));
  return <View style={[s.page, { backgroundColor: palette.background }]}><ScrollView contentContainerStyle={s.content}><View style={[s.hero, { backgroundColor: palette.softSurface, borderColor: palette.border }]}><View style={[s.heroRow, { flexDirection: isRTL ? "row-reverse" : "row" }]}><View style={[s.heroIcon, { backgroundColor: palette.primarySoft }]}><MaterialIcons name="auto-graph" color={palette.primary} size={25} /></View><View style={{ flex: 1 }}><Text style={[s.title, { color: palette.text, textAlign: isRTL ? "right" : "left" }]}>{copy.title}</Text><Text style={{ color: palette.muted, fontSize: 13, lineHeight: 20, textAlign: isRTL ? "right" : "left" }}>{copy.subtitle}</Text></View></View></View><View style={[s.statRow, { flexDirection: isRTL ? "row-reverse" : "row" }]}><Stat icon="menu-book" value={String(insights.totalEntries)} label={copy.total} palette={palette} /><Stat icon="local-fire-department" value={String(insights.streak)} label={copy.streak} palette={palette} /></View><View style={[s.card, { backgroundColor: palette.surface, borderColor: palette.border }]}><Text style={[s.heading, { color: palette.text, textAlign: isRTL ? "right" : "left" }]}>{copy.weekly}</Text><View style={[s.chart, { flexDirection: isRTL ? "row-reverse" : "row" }]}>{insights.week.map((day) => <View key={day.key} style={s.day}><View style={s.barSpace}><View style={[s.bar, { backgroundColor: palette.primary, height: day.total ? Math.max(8, (day.total / maxDaily) * 88) : 3 }]} /></View><Text style={{ color: palette.muted, fontSize: 11 }}>{day.label}</Text></View>)}</View><Text style={[s.note, { color: palette.muted, textAlign: isRTL ? "right" : "left" }]}>{copy.weeklyHint}</Text></View><View style={[s.card, { backgroundColor: palette.surface, borderColor: palette.border }]}><Text style={[s.heading, { color: palette.text, textAlign: isRTL ? "right" : "left" }]}>{copy.moods}</Text><View style={s.moods}>{MOOD_IDS.map((mood) => <View key={mood} style={[s.moodRow, { flexDirection: isRTL ? "row-reverse" : "row" }]}><MoodBadge mood={mood} palette={palette} language={settings.language} isRTL={isRTL} /><Text style={{ color: palette.text, fontWeight: "800", marginStart: isRTL ? 0 : "auto", marginEnd: isRTL ? "auto" : 0 }}>{insights.moodTotals[mood]}</Text></View>)}</View></View><View style={[s.active, { backgroundColor: palette.primarySoft, flexDirection: isRTL ? "row-reverse" : "row" }]}><MaterialIcons name="event-available" color={palette.primary} size={20} /><Text style={{ color: palette.text, flex: 1, fontSize: 13, fontWeight: "700", textAlign: isRTL ? "right" : "left" }}>{insights.activeWeekday === undefined ? copy.activeNone : `${copy.active}: ${copy.weekdays[insights.activeWeekday]}`}</Text></View></ScrollView></View>;
}

function Stat({ icon, value, label, palette }: { icon: ComponentProps<typeof MaterialIcons>["name"]; value: string; label: string; palette: ReturnType<typeof useDiary>["palette"] }) { return <View style={[s.stat, { backgroundColor: palette.surface, borderColor: palette.border }]}><MaterialIcons name={icon} size={20} color={palette.primary} /><Text style={[s.value, { color: palette.text }]}>{value}</Text><Text style={{ color: palette.muted, fontSize: 12, fontWeight: "700" }}>{label}</Text></View>; }

const s = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, gap: 14, paddingBottom: 36 }, hero: { borderWidth: 1, padding: 16, borderRadius: 20 }, heroRow: { gap: 12, alignItems: "center" }, heroIcon: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, title: { fontSize: 21, fontWeight: "900", marginBottom: 3 }, statRow: { gap: 10 }, stat: { flex: 1, borderWidth: 1, minHeight: 104, borderRadius: 18, padding: 14, gap: 4 }, value: { fontSize: 29, fontWeight: "900" }, card: { borderWidth: 1, borderRadius: 20, padding: 15, gap: 12 }, heading: { fontSize: 15, fontWeight: "900" }, chart: { gap: 9, justifyContent: "space-between", height: 126 }, day: { flex: 1, alignItems: "center", justifyContent: "flex-end", gap: 5 }, barSpace: { height: 96, justifyContent: "flex-end", width: "100%" }, bar: { borderRadius: 7, minHeight: 3, width: "100%" }, note: { fontSize: 12, lineHeight: 18 }, moods: { gap: 8 }, moodRow: { minHeight: 32, alignItems: "center" }, active: { borderRadius: 16, gap: 9, paddingHorizontal: 14, paddingVertical: 14, alignItems: "center" } });
