import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { fontName, languageName } from "@/lib/imanote/copy";
import { useDiary } from "@/lib/imanote/diary-context";
import type { AppAppearance, AppLanguage, EntryFont } from "@/lib/imanote/types";

function Option<T extends string>({ label, value, selected, onPress }: { label: string; value: T; selected: boolean; onPress: (v: T) => void }) { const { palette, isRTL } = useDiary(); return <Pressable onPress={() => onPress(value)} style={[s.option, { flexDirection: isRTL ? "row-reverse" : "row", borderColor: selected ? palette.primary : palette.border, backgroundColor: selected ? palette.primary : palette.surface }]}><Text style={{ color: selected ? "#fff" : palette.text, fontWeight: "700" }}>{label}</Text>{selected && <MaterialIcons name="check" color="#fff" size={18} />}</Pressable>; }
export default function SettingsScreen() { const { settings, updateSettings, requestLockChange, copy, palette, isRTL } = useDiary(); return <View style={[s.page, { backgroundColor: palette.background }]}><ScrollView contentContainerStyle={s.content}><Text style={[s.heading, { color: palette.text, textAlign: isRTL ? "right" : "left" }]}>{copy.settings}</Text><Text style={[s.label, { color: palette.muted, textAlign: isRTL ? "right" : "left" }]}>{copy.appearance}</Text><View style={s.group}>{(["blossom", "noir"] as AppAppearance[]).map((value) => <Option key={value} value={value} selected={settings.appearance === value} onPress={(appearance) => void updateSettings({ appearance })} label={value === "blossom" ? copy.blossom : copy.noir} />)}</View><Text style={[s.label, { color: palette.muted, textAlign: isRTL ? "right" : "left" }]}>{copy.language}</Text><View style={s.group}>{(["ar", "fr", "en"] as AppLanguage[]).map((value) => <Option key={value} value={value} selected={settings.language === value} onPress={(language) => void updateSettings({ language })} label={languageName(value, settings.language)} />)}</View><Text style={[s.label, { color: palette.muted, textAlign: isRTL ? "right" : "left" }]}>{copy.defaultFont}</Text><View style={s.group}>{(["classic", "clean", "mono"] as EntryFont[]).map((value) => <Option key={value} value={value} selected={settings.defaultFont === value} onPress={(defaultFont) => void updateSettings({ defaultFont })} label={fontName(value, settings.language)} />)}</View><Text style={[s.label, { color: palette.muted, textAlign: isRTL ? "right" : "left" }]}>{copy.privacy}</Text><Pressable onPress={() => Alert.alert(copy.privacy, copy.changeLock, [{ text: copy.cancel, style: "cancel" }, { text: copy.changeLock, style: "destructive", onPress: () => void requestLockChange() }])} style={[s.lock, { backgroundColor: palette.surface, borderColor: palette.border, flexDirection: isRTL ? "row-reverse" : "row" }]}><MaterialIcons name="lock-outline" size={20} color={palette.primary} /><Text style={{ color: palette.text, fontWeight: "800", flex: 1, textAlign: isRTL ? "right" : "left" }}>{copy.changeLock}</Text><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={22} color={palette.muted} /></Pressable><Text style={[s.note, { color: palette.muted, textAlign: isRTL ? "right" : "left" }]}>{copy.localOnly}</Text></ScrollView></View>; }
const s = StyleSheet.create({ page: { flex: 1 }, content: { padding: 20, paddingTop: 24, paddingBottom: 96 }, heading: { fontSize: 29, fontWeight: "800", marginBottom: 23 }, label: { fontSize: 13, fontWeight: "800", marginBottom: 8, marginTop: 17, textTransform: "uppercase" }, group: { gap: 7 }, option: { minHeight: 47, borderWidth: 1, borderRadius: 14, paddingHorizontal: 14, alignItems: "center", justifyContent: "space-between" }, lock: { minHeight: 57, borderWidth: 1, borderRadius: 17, paddingHorizontal: 14, alignItems: "center", gap: 11 }, note: { marginTop: 13, fontSize: 13 } });
